### PR TITLE
Bump fetchr to the latest version

### PR DESCRIPTION
**Pull request by Bazze**

### CODE REVIEW

**Comment by redonkulus** [comment]
You should get the latest automatically by npm. Are you seeing otherwise?

**Comment by Bazze** [comment]
Hmm, I'm not getting it with neither `npm install` nor `npm update`. However, I went into my `node_modules/fluxible-plugin-fetchr` directory and then did a `npm update`, that did the trick. But I guess you should still want to bump the version?

**Comment by redonkulus** [comment]
Which version of npm are you using?

**Comment by Bazze** [comment]
@redonkulus: 2.10.1

**Comment by tleunen** [comment]
Tested and I'm getting 0.5.15 on my side

**Comment by Bazze** [comment]
I do get it if I delete my `node_modules` folder and then do an install.

**Comment by Vijar** [comment]
Yeah, it only works for a fresh npm install (delete node_modules) .

If you already have an old version that satisfies the semver npm wouldn't
automatically update it to latest.

**Pull request closed without merging**
